kosc_test/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('montparnasse_bar.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

montparnasse_bar/urls.py
from django.urls import path
from django.views.generic.base import TemplateView

from . import views

app_name = 'montparnasse_bar'
urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('api/reference', views.reference, name='reference'),
    path('api/reference/modify', views.reference_modify, name='reference_modify'),
    path('api/bars', views.bar, name='bar'),
    path('api/bars/modify', views.bar_modify, name='bar_modify'),
    path('api/stock/<int:bar_id>', views.stock, name='stock'),
    path('api/bars/ranking', views.ranking, name='ranking'),
    path('api/menu', views.menu, name='menu'),
]

montparnasse_bar/models.py
from django.db import models


class Beer(models.Model):
    ref = models.CharField(max_length=200)
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=200)


class Bar(models.Model):
    name = models.CharField(max_length=200)


class Stock(models.Model):
    bar = models.ForeignKey(Bar, on_delete=models.CASCADE)
    beer = models.ForeignKey(Beer, on_delete=models.CASCADE)
    stock = models.IntegerField(default=0)

montparnasse_bar/views.py
from django.shortcuts import render, get_list_or_404
from .models import Beer, Bar, Stock
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib.admin.views.decorators import staff_member_required
from .form import ReferenceForm, BarForm


@login_required
def reference(request):
    references = get_list_or_404(Beer)
    page = request.GET.get('page', 1)
    paginator = Paginator(references, 10)
    try:
        references = paginator.page(page)
    except PageNotAnInteger:
        references = paginator.page(1)
    except EmptyPage:
        references = paginator.page(paginator.num_pages)
    form = ReferenceForm()
    return render(request, 'montparnasse_bar/references.html', {'references': references, 'form': form})


@staff_member_required
def reference_modify(request):
    if 'delete' in request.POST:
        beer = get_list_or_404(Beer, id=request.POST['choice'])
        for b in beer:
            b.delete()
    elif 'add' in request.POST:
        beer = Beer()
        beer.ref = request.POST['ref']
        beer.name = request.POST['name']
        beer.description = request.POST['description']
        beer.save()
    elif 'modify' in request.POST:
        beers = get_list_or_404(Beer, id=request.POST['id'])
        for beer in beers:
            beer.ref = request.POST['reference']
            beer.name = request.POST['name']
            beer.description = request.POST['description']
            beer.save()
    return HttpResponseRedirect(reverse('montparnasse_bar:reference'))


@login_required
def bar(request):
    bars = get_list_or_404(Bar)
    page = request.GET.get('page', 1)
    paginator = Paginator(bars, 10)
    try:
        bars = paginator.page(page)
    except PageNotAnInteger:
        bars = paginator.page(1)
    except EmptyPage:
        bars = paginator.page(paginator.num_pages)
    form = BarForm()
    return render(request, 'montparnasse_bar/bars.html', {'bars': bars, 'form': form})


@staff_member_required
def bar_modify(request):
    if 'delete' in request.POST:
        bar = get_list_or_404(Bar, id=request.POST['choice'])
        for b in bar:
            b.delete()
    elif 'add' in request.POST:
        bar = Bar()
        bar.id = request.POST['pk']
        bar.name = request.POST['name']
        bar.save()
    elif 'modify' in request.POST:
        bars = get_list_or_404(Bar, id=request.POST['id'])
        for bar in bars:
            bar.name = request.POST['name']
            bar.save()
    return HttpResponseRedirect(reverse('montparnasse_bar:bar'))


@login_required
def stock(request, bar_id):
    stocks = Stock.objects.all()
    # stocks = get_list_or_404(Stock, bar_id=bar_id)
    page = request.GET.get('page', 1)
    paginator = Paginator(stocks, 10)
    try:
        stocks = paginator.page(page)
    except PageNotAnInteger:
        stocks = paginator.page(1)
    except EmptyPage:
        stocks = paginator.page(paginator.num_pages)
    return render(request, 'montparnasse_bar/stock.html', {'stocks': stocks})


@login_required
def ranking(request):
    bars_miss = get_list_or_404(Stock, stock=0)
    bars = get_list_or_404(Bar)
    all = {bar.id for bar in bars}
    miss = {bar.bar_id for bar in bars_miss}
    all -= miss
    return render(request, 'montparnasse_bar/ranking.html', {'all': list(all), 'miss': list(miss)})


def menu(request):
    stocks = get_list_or_404(Stock)
    available = dict()
    unavailable = dict()
    for stock in stocks:
        beer = stock.beer
        if stock.stock > 0:
            if beer.id in unavailable:
                unavailable.pop(beer.id)
            available[beer.id] = beer
        elif beer.id not in available:
            unavailable[beer.id] = beer
    results = list()
    for id_, beer in available.items():
        results.append({'ref': beer.ref, 'name': beer.name, 'description': beer.description,
                        'availibility': 'available'})
    for id_, beer in unavailable.items():
        results.append({'ref': beer.ref, 'name': beer.name, 'description': beer.description,
                        'availibility': 'out of stock'})
    page = request.GET.get('page', 1)
    paginator = Paginator(results, 10)
    try:
        results = paginator.page(page)
    except PageNotAnInteger:
        results = paginator.page(1)
    except EmptyPage:
        results = paginator.page(paginator.num_pages)
    return render(request, 'montparnasse_bar/menu.html', {'results': results})

montparnasse_bar/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>Kosc Telecom Test</title>
  </head>
  <body>
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-8">
          <h1 class="mt-2">Montparnasse Bar</h1>
          <hr class="mt-0 mb-4">
          {% block content %}
          {% endblock %}
        </div>
      </div>
    </div>
  </body>
</html>

montparnasse_bar/templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  Hi {{ user.username }}!
  <p><a href="{% url 'logout' %}">logout</a></p>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">login</a>
{% endif %}
{% endblock %}

montparnasse_bar/templates/montparnasse_bar/bar_order.html
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'montparnasse_bar:order' beers_id%}" method="post">
{% csrf_token %}
    <label>Beer List</label><br />
       <select>
           {% for beer in beers %}
               <option value="{{beer.id}}">{{beer.name}}</option>
            {% endfor %}
        </select>
<input type="submit" value="Order">
</form>

montparnasse_bar/templates/montparnasse_bar/bars.html
{% extends 'base.html' %}

{% block content %}
<form action="{% url 'montparnasse_bar:bar_modify' %}" method="post">
{% csrf_token %}
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Name</th>
        <th>Étage</th>
        {% if request.user.is_staff %}
            <th>Delete</th>
          {% endif %}
      </tr>
    </thead>
    <tbody>
      {% for bar in bars %}
        <tr>
            <td>{{ bar.id }}</td>
            {% if request.user.is_staff %}
              <td><input type="text" name="name" value={{ bar.name }}>
                  <input type="hidden" name="id" value={{ bar.id }}>
              </td>
          {% else %}
              <td>{{ bar.name }}</td>
          {% endif %}
          {% if request.user.is_staff %}
                <td><input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ bar.id }}"></td>
          {% endif %}
        </tr>
      {% endfor %}
    </tbody>
  </table>
  {% if request.user.is_staff %}
        <button type="submit" name="modify">Modify</button>
        <button type="submit" name="delete">Delete</button>
    {% endif %}
</form>
{% if bars.has_other_pages %}
  <ul class="pagination">
    {% if bars.has_previous %}
      <li><a href="?page={{ bars.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in bars.paginator.page_range %}
      {% if bars.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if bars.has_next %}
      <li><a href="?page={{ bars.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}
{% if request.user.is_staff %}
    <form action="{% url 'montparnasse_bar:bar_modify' %}" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <button type="submit" name="add">Add</button>
    </form>
{% endif %}
{% endblock %}

montparnasse_bar/templates/montparnasse_bar/menu.html
{% extends 'base.html' %}

{% block content %}
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Ref</th>
      <th>Name</th>
      <th>Description</th>
      <th>Availibility</th>
    </tr>
  </thead>
  <tbody>
    {% for result in results %}
      <tr>
        <td>{{ result.ref }}</td>
        <td>{{ result.name }}</td>
        <td>{{ result.description }}</td>
        <td>{{ result.availibility }}</td>
      </tr>
    {% endfor %}
  </tbody>
</table>

{% if results.has_other_pages %}
  <ul class="pagination">
    {% if results.has_previous %}
      <li><a href="?page={{ results.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in results.paginator.page_range %}
      {% if results.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if results.has_next %}
      <li><a href="?page={{ results.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}
{% endblock %}

montparnasse_bar/templates/montparnasse_bar/ranking.html
{% extends 'base.html' %}

{% block content %}

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Bars</th>
    </tr>
  </thead>
  <tbody>
      <tr>
        <td>all_stocks</td>
        <td>Liste des comptoirs qui ont toutes les références en stock</td>
        <td>{{all|join:", "}}</td>
      </tr>
      <tr>
        <td>miss_at_least_one</td>
        <td>Liste des comptoirs qui ont au moins une référence épuisée</td>
        <td>{{miss|join:", "}}</td>
      </tr>
  </tbody>
</table>
{% endblock %}

montparnasse_bar/templates/montparnasse_bar/references.html
{% extends 'base.html' %}

{% block content %}
<form action="{% url 'montparnasse_bar:reference_modify' %}" method="post" class="form form-inline">
    {% csrf_token %}
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Ref</th>
          <th>Name</th>
          <th>Description</th>
          {% if request.user.is_staff %}
            <th>Delete</th>
          {% endif %}
        </tr>
      </thead>
      <tbody>
        {% for reference in references %}
          <tr>
              {% if request.user.is_staff %}
                  <td><input type="text" name="reference" value={{ reference.ref }}></td>
                  <td><input type="text" name="name" value={{ reference.name }}></td>
                  <td><input type="text" name="description" value={{ reference.description }}>
                      <input type="hidden" name="id" value={{ reference.id }}>
                  </td>
              {% else %}
                  <td>{{ reference.ref }}</td>
                  <td>{{ reference.name }}</td>
                  <td>{{ reference.description }}</td>
              {% endif %}
            {% if request.user.is_staff %}
                <td><input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ reference.id }}"></td>
            {% endif %}
          </tr>
        {% endfor %}
      </tbody>
    </table>
    {% if request.user.is_staff %}
        <button type="submit" name="modify">Modify</button>
        <button type="submit" name="delete">Delete</button>
    {% endif %}
</form>

{% if references.has_other_pages %}
  <ul class="pagination">
    {% if references.has_previous %}
      <li><a href="?page={{ references.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in references.paginator.page_range %}
      {% if references.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if references.has_next %}
      <li><a href="?page={{ references.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}
{% if request.user.is_staff %}
    <form action="{% url 'montparnasse_bar:reference_modify' %}" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <button type="submit" name="add">Add</button>
    </form>
{% endif %}
{% endblock %}

montparnasse_bar/templates/montparnasse_bar/stock.html
{% extends 'base.html' %}

{% block content %}
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Ref</th>
      <th>Name</th>
      <th>Description</th>
      <th>Stock</th>
    </tr>
  </thead>
  <tbody>
    {% for stock in stocks %}
      <tr>
        <td>{{ stock.beer.ref }}</td>
        <td>{{ stock.beer.name }}</td>
        <td>{{ stock.beer.description }}</td>
        <td>{{ stock.stock }}</td>
      </tr>
    {% endfor %}
  </tbody>
</table>

{% if stocks.has_other_pages %}
  <ul class="pagination">
    {% if stocks.has_previous %}
      <li><a href="?page={{ stocks.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in stocks.paginator.page_range %}
      {% if stocks.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if stocks.has_next %}
      <li><a href="?page={{ stocks.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}
{% endblock %}